language: node_js
node_js:
 - "6.1.0"
addons:
  ssh_known_hosts: ramon-james.com
before_install:
  - bash scripts/install.sh
script:
  - bash scripts/build.sh
  - bash scripts/test.sh
after_success:
  - bash scripts/deploy.sh
