# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md
FROM node:6.3.1-slim
RUN groupadd -r build && useradd -r -g build build
RUN mkdir -p /var/www/ramon-james.com
ADD build.tar.gz /var/www/ramon-james.com/
RUN npm install forever -g
RUN NODE_ENV=production forever start /var/www/ramon-james.com/index.js
EXPOSE 8080

